
version: '3.9'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - DEBUG=False
      - SECRET_KEY=secret_key
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
